language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- gem update --system $RUBYGEMS_VERSION
- gem --version
- gem install bundler
- bundle --version
- bash test/setup_ubuntu.bash
bundler_args: --binstubs
script: rvmsudo_secure_path=1 rvmsudo UNREACHABLE_ROUTE=192.0.2.1 UNREACHABLE_HOST=`test/find_unreachable_host.bash` PING2_CLASSES=$PING2_CLASSES bin/rake test
matrix:
  include:
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: 2.1.0
    - rvm: jruby-19mode
    - rvm: rbx-2.2.6
    # upcoming releases
    - rvm: rbx
      env: TESTOPTS=-v
    - rvm: jruby-head
      env: TESTOPTS=-v
    - rvm: ruby-head
      env: TESTOPTS=-v
    # show bugs
    - rvm: rbx
      env: TESTOPTS=-v PING2_CLASSES=all
    - rvm: ruby-head
      env: TESTOPTS=-v PING2_CLASSES=all
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-head
