language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- gem update --system $RUBYGEMS_VERSION
- gem --version
- gem install bundler
- bundle --version
bundler_args: --binstubs
script: 
- bin/rake build
- . test/setup_ubuntu.bash ; rvmsudo_secure_path=1 rvmsudo `env | egrep '^TRAVIS|PING2|UNREACHABLE'` bin/rake test
matrix:
  include:
    - rvm: 1.9.3
      env: RUBYGEMS_VERSION=2.7.10
    - rvm: 2.0.0
      env: RUBYGEMS_VERSION=2.7.10
    - rvm: 2.1.10
      env: RUBYGEMS_VERSION=2.7.10
    - rvm: 2.2.9
      env: RUBYGEMS_VERSION=2.7.10
    - rvm: 2.3.6
    - rvm: 2.4.3
    - rvm: 2.5.8
    - rvm: 2.6.6
    - rvm: 2.8.1
    - rvm: ruby-head
      env: TESTOPTS=-v
  allow_failures:
    - rvm: ruby-head
      env: TESTOPTS=-v
