language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- gem update --system $RUBYGEMS_VERSION
- gem --version
- gem install bundler
- bundle --version
- bash test/setup_ubuntu.bash
bundler_args: --binstubs
script: rvmsudo_secure_path=1 rvmsudo UNREACHABLE_ROUTE=192.0.2.1 UNREACHABLE_HOST=`test/find_unreachable_host.bash` EXCLUDE=$EXCLUDE bin/rake test
matrix:
  include:
    - rvm: 1.8.7
      env: EXCLUDE=TCP_SERVICE_CHECK_UNUSED_PORT_BUG
    - rvm: 1.9.2
      env: EXCLUDE=TCP_SERVICE_CHECK_UNUSED_PORT_BUG
    - rvm: 1.9.3
      env: EXCLUDE=TCP_SERVICE_CHECK_UNUSED_PORT_BUG
    - rvm: 2.0.0
      env: EXCLUDE=TCP_SERVICE_CHECK_UNUSED_PORT_BUG
    - rvm: 2.1.0
      env: EXCLUDE=TCP_SERVICE_CHECK_UNUSED_PORT_BUG
    # https://jira.codehaus.org/browse/JRUBY-5897 - jruby doesn't support raw sockets
    # jruby timeout doesn't work with udp sockets
    # jruby: tcp tests failing with Errno::ECONNREFUSED to localhost port 22
    - rvm: jruby-19mode
      env: EXCLUDE=udp,icmp,tcp,HTTP_PING_DOES_NOT_TIMEOUT_BUG,TCP_SERVICE_CHECK_UNUSED_PORT_BUG
    - rvm: rbx-2.2.6
      env: EXCLUDE=icmp,TCP_SERVICE_CHECK_UNUSED_PORT_BUG
    # show bugs
    - rvm: ruby-head
      env: TESTOPTS=-v
    # upcoming releases
    - rvm: ruby-head
      env: TESTOPTS=-v EXCLUDE=TCP_SERVICE_CHECK_UNUSED_PORT_BUG
    - rvm: rbx
      env: TESTOPTS=-v EXCLUDE=icmp,TCP_SERVICE_CHECK_UNUSED_PORT_BUG
    - rvm: jruby-head
      env: TESTOPTS=-v EXCLUDE=udp,icmp,tcp,TCP_SERVICE_CHECK_UNUSED_PORT_BUG
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-head

